-- Step 91: Reports 2 — Report definition table + API
-- Target: shared schema in polyaccess database
--
-- Creates the report_definitions table that stores band-oriented report
-- configurations consumed by the Python rendering engine (server/reports/).
--
-- Migration: idempotent (IF NOT EXISTS, ON CONFLICT)

BEGIN;

-- ═══════════════════════════════════════════════════════════════
-- 0. Ensure pgcrypto extension for gen_random_uuid()
-- ═══════════════════════════════════════════════════════════════

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ═══════════════════════════════════════════════════════════════
-- 1. report_definitions table
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS shared.report_definitions (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name            VARCHAR(255) NOT NULL,
  caption         VARCHAR(255) NOT NULL,
  description     TEXT,
  category        VARCHAR(100) NOT NULL DEFAULT 'Other',
  template_file   TEXT NOT NULL,
  output_formats  TEXT[] NOT NULL DEFAULT '{pdf}',
  source_table    TEXT,
  filterable      BOOLEAN NOT NULL DEFAULT false,
  parameters      JSONB NOT NULL DEFAULT '[]'::jsonb,
  bands           JSONB NOT NULL DEFAULT '{}'::jsonb,
  visible_to_roles TEXT[] NOT NULL DEFAULT '{}',
  auto_generate   JSONB,
  enabled         BOOLEAN NOT NULL DEFAULT true,
  company_id      INTEGER NOT NULL DEFAULT 1,
  created_by      VARCHAR(100),
  updated_by      VARCHAR(100),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE shared.report_definitions IS
  'Report definitions for the band-oriented rendering engine (server/reports/).';

COMMENT ON COLUMN shared.report_definitions.id IS 'Primary key, UUID generated by pgcrypto.';
COMMENT ON COLUMN shared.report_definitions.name IS 'Unique slug-like name (e.g., invoice, customer-statements).';
COMMENT ON COLUMN shared.report_definitions.caption IS 'Human-readable title shown in the report browser.';
COMMENT ON COLUMN shared.report_definitions.description IS 'Optional longer description of the report purpose.';
COMMENT ON COLUMN shared.report_definitions.category IS 'Group/category for organization (Financial, Inventory, Production, Other).';
COMMENT ON COLUMN shared.report_definitions.template_file IS 'Path to .ods template file relative to templates/ directory.';
COMMENT ON COLUMN shared.report_definitions.output_formats IS 'Allowed output formats (pdf, csv, xlsx, html, ods).';
COMMENT ON COLUMN shared.report_definitions.source_table IS 'Primary DB table name for the report data source.';
COMMENT ON COLUMN shared.report_definitions.filterable IS 'Whether parameter entry is shown before render.';
COMMENT ON COLUMN shared.report_definitions.parameters IS 'Array of ReportParameter objects for user input.';
COMMENT ON COLUMN shared.report_definitions.bands IS 'Object with title/header/detail/summary/footer/cover band row configs.';
COMMENT ON COLUMN shared.report_definitions.visible_to_roles IS 'Array of role names that can see/run this report.';
COMMENT ON COLUMN shared.report_definitions.auto_generate IS 'Optional ScheduleConfig object for auto-generation.';
COMMENT ON COLUMN shared.report_definitions.enabled IS 'Whether this report is active and available.';
COMMENT ON COLUMN shared.report_definitions.company_id IS 'Tenant/company scoping.';

-- Unique constraint on name (unique across all companies for simplicity)
CREATE UNIQUE INDEX IF NOT EXISTS idx_report_definitions_name
  ON shared.report_definitions (name);

-- Index for filtering by category
CREATE INDEX IF NOT EXISTS idx_report_definitions_category
  ON shared.report_definitions (category);

-- Index for active report queries
CREATE INDEX IF NOT EXISTS idx_report_definitions_enabled
  ON shared.report_definitions (enabled);

-- Composite index for typical list queries
CREATE INDEX IF NOT EXISTS idx_report_definitions_cat_enabled
  ON shared.report_definitions (category, enabled);

-- Index for recent updates listing
CREATE INDEX IF NOT EXISTS idx_report_definitions_updated
  ON shared.report_definitions (updated_at DESC);

-- Updated_at trigger
CREATE OR REPLACE FUNCTION shared.trigger_set_report_def_updated()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_report_definitions_updated ON shared.report_definitions;
CREATE TRIGGER trg_report_definitions_updated
  BEFORE UPDATE ON shared.report_definitions
  FOR EACH ROW
  EXECUTE FUNCTION shared.trigger_set_report_def_updated();

-- ═══════════════════════════════════════════════════════════════
-- 2. Seed data — placeholder report definitions
-- ═══════════════════════════════════════════════════════════════

INSERT INTO shared.report_definitions
  (name, caption, description, category, template_file, output_formats,
   source_table, filterable, parameters, bands, visible_to_roles, enabled)
VALUES
  -- ── Financial ──
  ('invoice',
   'Invoice',
   'Customer invoice with line items, taxes, and totals.',
   'Financial',
   'templates/invoice.ods',
   ARRAY['pdf','xlsx'],
   'orders',
   true,
   '[{"name":"order_id","label":"Order ID","type":"text","required":true}]'::jsonb,
   '{"title":{"start_row":0,"end_row":2},"header":{"start_row":3,"end_row":3},"detail":{"start_row":4,"end_row":4},"summary":{"start_row":6,"end_row":6},"footer":{"start_row":8,"end_row":9}}'::jsonb,
   ARRAY['admin','accounting','sales'],
   true),

  ('invoice-summary',
   'Invoice Summary',
   'Aggregated invoice data over a date range.',
   'Financial',
   'templates/invoice-summary.ods',
   ARRAY['pdf','csv','xlsx'],
   'orders',
   true,
   '[{"name":"date_from","label":"From Date","type":"date","required":true},{"name":"date_to","label":"To Date","type":"date","required":true}]'::jsonb,
   '{"title":{"start_row":0,"end_row":1},"detail":{"start_row":2,"end_row":2},"summary":{"start_row":4,"end_row":4},"footer":{"start_row":6,"end_row":6}}'::jsonb,
   ARRAY['admin','accounting'],
   true),

  ('credit-note',
   'Credit Note',
   'Credit note / refund document for returned goods or adjustments.',
   'Financial',
   'templates/credit-note.ods',
   ARRAY['pdf','xlsx'],
   'credit_notes',
   true,
   '[{"name":"credit_note_id","label":"Credit Note ID","type":"text","required":true}]'::jsonb,
   '{"title":{"start_row":0,"end_row":2},"header":{"start_row":3,"end_row":3},"detail":{"start_row":4,"end_row":4},"summary":{"start_row":6,"end_row":6},"footer":{"start_row":8,"end_row":9}}'::jsonb,
   ARRAY['admin','accounting'],
   true),

  ('customer-statement',
   'Customer Statement',
   'Periodic statement showing all transactions for a customer.',
   'Financial',
   'templates/customer-statement.ods',
   ARRAY['pdf'],
   'customers',
   true,
   '[{"name":"customer_id","label":"Customer","type":"lookup","table":"customers","required":true},{"name":"date_from","label":"From Date","type":"date","required":false},{"name":"date_to","label":"To Date","type":"date","required":false}]'::jsonb,
   '{"title":{"start_row":0,"end_row":2},"header":{"start_row":3,"end_row":3},"detail":{"start_row":4,"end_row":4},"summary":{"start_row":6,"end_row":6},"footer":{"start_row":8,"end_row":8}}'::jsonb,
   ARRAY['admin','accounting','sales'],
   true),

  ('sales-by-customer',
   'Sales by Customer',
   'Sales totals grouped by customer for a date range.',
   'Financial',
   'templates/sales-by-customer.ods',
   ARRAY['pdf','csv','xlsx'],
   'orders',
   true,
   '[{"name":"date_from","label":"From Date","type":"date","required":true},{"name":"date_to","label":"To Date","type":"date","required":true}]'::jsonb,
   '{"title":{"start_row":0,"end_row":1},"detail":{"start_row":2,"end_row":2},"summary":{"start_row":4,"end_row":4}}'::jsonb,
   ARRAY['admin','accounting','management'],
   true),

  -- ── Inventory ──
  ('inventory-list',
   'Inventory List',
   'Complete list of all inventory items with quantities and valuation.',
   'Inventory',
   'templates/inventory-list.ods',
   ARRAY['pdf','csv','xlsx'],
   'inventory',
   false,
   '[]'::jsonb,
   '{"title":{"start_row":0,"end_row":1},"detail":{"start_row":2,"end_row":2},"footer":{"start_row":4,"end_row":4}}'::jsonb,
   ARRAY['admin','inventory','production'],
   true),

  ('stock-valuation',
   'Stock Valuation',
   'Current stock value by item with cost and selling price.',
   'Inventory',
   'templates/stock-valuation.ods',
   ARRAY['pdf','xlsx'],
   'inventory',
   false,
   '[]'::jsonb,
   '{"title":{"start_row":0,"end_row":1},"detail":{"start_row":2,"end_row":2},"summary":{"start_row":4,"end_row":4}}'::jsonb,
   ARRAY['admin','accounting','inventory'],
   true),

  ('low-stock-alert',
   'Low Stock Alert',
   'Items below reorder threshold requiring procurement action.',
   'Inventory',
   'templates/low-stock-alert.ods',
   ARRAY['pdf','csv'],
   'inventory',
   false,
   '[]'::jsonb,
   '{"title":{"start_row":0,"end_row":1},"detail":{"start_row":2,"end_row":2}}'::jsonb,
   ARRAY['admin','inventory','production'],
   true),

  ('inventory-movement',
   'Inventory Movement',
   'Stock movement transactions (receipts, issues, adjustments) for a date range.',
   'Inventory',
   'templates/inventory-movement.ods',
   ARRAY['pdf','csv','xlsx'],
   'inventory_transactions',
   true,
   '[{"name":"date_from","label":"From Date","type":"date","required":true},{"name":"date_to","label":"To Date","type":"date","required":true}]'::jsonb,
   '{"title":{"start_row":0,"end_row":1},"header":{"start_row":2,"end_row":2},"detail":{"start_row":3,"end_row":3},"footer":{"start_row":5,"end_row":5}}'::jsonb,
   ARRAY['admin','inventory'],
   true),

  -- ── Production ──
  ('work-order',
   'Work Order',
   'Production work order with materials, steps, and yield.',
   'Production',
   'templates/work-order.ods',
   ARRAY['pdf'],
   'workorders',
   true,
   '[{"name":"workorder_id","label":"Work Order ID","type":"text","required":true}]'::jsonb,
   '{"title":{"start_row":0,"end_row":2},"header":{"start_row":3,"end_row":3},"detail":{"start_row":4,"end_row":4},"summary":{"start_row":6,"end_row":6},"footer":{"start_row":8,"end_row":8}}'::jsonb,
   ARRAY['admin','production'],
   true),

  ('roast-log',
   'Roast Log',
   'Detailed roast profile log with time, temperature, and batch data.',
   'Production',
   'templates/roast-log.ods',
   ARRAY['pdf','csv'],
   'roast_batches',
   true,
   '[{"name":"date_from","label":"From Date","type":"date","required":true},{"name":"date_to","label":"To Date","type":"date","required":true}]'::jsonb,
   '{"title":{"start_row":0,"end_row":1},"header":{"start_row":2,"end_row":2},"detail":{"start_row":3,"end_row":3},"footer":{"start_row":5,"end_row":5}}'::jsonb,
   ARRAY['admin','production','quality'],
   true),

  ('batch-yield-report',
   'Batch Yield Report',
   'Yield analysis by batch, bean, and roast profile.',
   'Production',
   'templates/batch-yield.ods',
   ARRAY['pdf','csv','xlsx'],
   'roast_batches',
   true,
   '[{"name":"date_from","label":"From Date","type":"date","required":true},{"name":"date_to","label":"To Date","type":"date","required":true}]'::jsonb,
   '{"title":{"start_row":0,"end_row":1},"detail":{"start_row":2,"end_row":2},"summary":{"start_row":4,"end_row":4}}'::jsonb,
   ARRAY['admin','production','management'],
   true),

  ('production-schedule',
   'Production Schedule',
   'Upcoming and in-progress production schedule.',
   'Production',
   'templates/production-schedule.ods',
   ARRAY['pdf'],
   'workorders',
   false,
   '[]'::jsonb,
   '{"title":{"start_row":0,"end_row":1},"detail":{"start_row":2,"end_row":2}}'::jsonb,
   ARRAY['admin','production','sales'],
   true)

ON CONFLICT (name) DO UPDATE SET
  caption         = EXCLUDED.caption,
  description     = EXCLUDED.description,
  category        = EXCLUDED.category,
  template_file   = EXCLUDED.template_file,
  output_formats  = EXCLUDED.output_formats,
  source_table    = EXCLUDED.source_table,
  filterable      = EXCLUDED.filterable,
  parameters      = EXCLUDED.parameters,
  bands           = EXCLUDED.bands,
  visible_to_roles = EXCLUDED.visible_to_roles,
  enabled         = EXCLUDED.enabled,
  updated_at      = NOW();

COMMIT;
